# Generated by Django 6.0.5 on 2026-07-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommarce_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='full_address',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default',
        ),
    ]
